---

- name: "Upgrade primary"
  community.docker.docker_container_exec:
    container: "{{ container_name }}"
    command: "mariadb-upgrade --user={{ mariadb_secrets.superuser.user }} --host=127.0.0.1 --port=3306 --verbose --password={{ mariadb_secrets.superuser.password }}"
  register: _upgrade_result
  changed_when: >-
    "MariaDB is already upgraded" not in _upgrade_result.stdout
  tags:
    - mariadb.upgrade


- name: "Read binlog position"
  ansible.builtin.slurp:
    src: "{{ binlog_position_path }}"
  register: _binlog_position
  tags:
    - mariadb.binlogpos

- name: "Interprete binlog_position"
  ansible.builtin.set_fact:
    _binlog_raw: "{{ _binlog_position.content | b64decode | from_json }}" 
  tags:
    - mariadb.binlogpos

- name: Extract interesting part from binlog_position output
  ansible.builtin.set_fact:
    _binlog: "{{ _binlog_raw['query_result'][0][0] }}" 
  tags:
    - mariadb.binlogpos

- name: "Debug binlog position"
  ansible.builtin.debug:
    var: _binlog
  tags:
    - mariadb.binlogpos


- name: "Debug binlog position"
  ansible.builtin.debug:
    msg: "position: {{ _binlog.Position }}     file: {{ _binlog.File }}"
  tags:
    - mariadb.binlogpos

# - name: "Debug binlog position"
#   ansible.builtin.debug:
#     msg: "{{ _binlog['query_result'][0][0]['Position'] }}"
#   tags:
#     - mariadb.binlogpos
