---
- name: "Read binlog position file"
  ansible.builtin.shell:
    cmd: 
      awk '{printf $3; exit;}' {{ input_backup_dir }}/mariadb_backup_binlog_info
  register: _binlog_filecontent
  tags:
    - mariadb.binlogpos

- name: "Transform the binlog file content to usable variable"
  ansible.builtin.set_fact:
    _binlog: "{{ _binlog_filecontent.stdout }}"
  tags:
    - mariadb.binlogpos

- name: "Debug binlog position"
  ansible.builtin.debug:
    var: _binlog
  tags:
    - mariadb.binlogpos