- name: "MariaDB VM + service"
  hosts: vms_test_master
    # - vms_test_slave
  gather_facts: no
  roles:
    - role: roles/mariadb-vm


- name: "MariaDB VM + service"
  hosts: vms_test_slave
  gather_facts: no
  roles:
    - role: roles/mariadb-vm
