---
# # This set of tasks will run only an a pristine server: no data should be present

# # TODO: add task with tag "nuke" to restart from scrach deleting all the data

- name: Check if MariaDB initial data folder exists
  ansible.builtin.stat:
    path: "{{ mariadb_data_path }}"
  register: _mariadb_data_dir

- fail:
    msg: The MariaDB data directory is already present. Aborting."
  when: _mariadb_data_dir.stat.exists

- name: Ensure mandatory directories
  with_items:
    - "{{ mariadb_data_path }}"
    - "{{ mariadb_cnf_path | dirname }}"
    - "{{ output_backup_dir }}"
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory

# MariaDB 10.4 can't import database dump created before 10.4: https://jira.mariadb.org/browse/MDEV-22127
- name: Prefetch remote original data
  shell:
    cmd: "rsync -av {{ old_data_source }}/ {{ mariadb_data_path }}/"
  vars:
    ansible_ssh_extra_args: -A
  # when:
  #   - not _mariadb_data_dir.stat.exists

- name: Stop writes into the original DB (Varnish tricks...)
  ansible.builtin.pause:
    prompt: "Please stop wp-admin from Varnish and FLUSH TABLES WITH READ LOCK on the old master server"

- name: One more quick sync of remote original data
  shell:
    cmd: "rsync -av {{ old_data_source }}/ {{ mariadb_data_path }}/"
  vars:
    ansible_ssh_extra_args: -A

- name: MariaDB_run
  include_tasks:
    file: run.yml
    apply:
      tags:
        - mariadb.initialize

- name: Make sure the DB have started
  ansible.builtin.pause:
    prompt: "Please Make sure the DB have started. Then press enter to start DB upgrade"

- name: "Upgrade primary"
  community.docker.docker_container_exec:
    container: "{{ container_name }}"
    command: "mariadb-upgrade --user={{ mariadb_secrets.superuser.user }} --host=127.0.0.1 --port=3306 --verbose --password={{ mariadb_secrets.superuser.password }}"
  register: _upgrade_result
  changed_when: >-
    "MariaDB is already upgraded" not in _upgrade_result.stdout

- name: "Create database user for replica"
  with_items: "{{ replica_hostnames }}"
  community.mysql.mysql_query:
    login_user: "{{ mariadb_secrets.superuser.user }}"
    login_password: "{{ mariadb_secrets.superuser.password }}"
    login_host: 127.0.0.1
    login_port: "{{ mariadb_port }}"
    query: >
      GRANT REPLICATION SLAVE ON *.* 
        TO '{{ mariadb_secrets.replicator.user}}'@'{{ item }}' 
        IDENTIFIED BY PASSWORD '{{ mariadb_secrets.replicator.password }}'

# TODO: for some reason this does not work. Why?
# - name: Create database user for replica
#   community.mysql.mysql_user:
#     name: "{{ mariadb_secrets.replicator.user }}"
#     password: "{{ mariadb_secrets.replicator.password }}"
#     host: "%"
#     priv: '*.*:REPLICATION SLAVE'
#     state: present
#     login_user: "{{ mariadb_secrets.superuser.user }}"
#     login_password: "{{ mariadb_secrets.superuser.password }}"

- name: "Backup primary to transfer backup directory"
  community.docker.docker_container_exec:
    container: "{{ container_name }}"
    command: "{{ item }}"
  with_items:
    - "rm -rf /var/mariadb_backup/*"
    - "/usr/bin/mariadb-backup --backup --target-dir=/var/mariadb_backup --user={{ mariadb_secrets.superuser.user }} --password={{ mariadb_secrets.superuser.password }} --binlog-info=ON"
    - "/usr/bin/mariadb-backup --prepare --target-dir=/var/mariadb_backup"
    # TODO: both commands output "completed OK!" if correctly finished
  register: _backup_result

- name: backup output
  ansible.builtin.debug:
    var: _backup_result

# Now it is time to switch the virtual IP:
# On the old primary (futur replica) server:
# ip ad del 128.178.109.64/24 dev ens192
# On the new primary server:
# ip addr add 128.178.109.64/24 dev ens192 && arpspoof -i ens192 -t 128.178.109.1 128.178.109.64
# The re-enable writing mode on wordpress
