---

- name: Ensure  my.cnf file
  ansible.builtin.template:
    src: my.cnf
    dest: "{{ mariadb_cnf_path }}"

- name: Ensure MariaDB container
  community.general.docker_container:
    name: '{{ container_name }}'
    state: started
    image: "mariadb:{{ mariadb_version }}"
    restart_policy: "unless-stopped"
    env:
      MARIADB_ROOT_PASSWORD: "{{ mariadb_secrets.root_password }}"
    ports:
      - "{{ mariadb_port }}:3306"
    volumes:
      - "{{ mariadb_cnf_path }}:/etc/mysql/mariadb.conf.d/my.cnf"
      - "{{ mariadb_data_path }}:/var/lib/mysql"
      - "{{ output_backup_dir }}:/var/mariadb_backup"
  tags:
    - mariadb.container


