mariadb_version: 11.4
# old_mariadb_version: 5.5

mariadb_binlog_basepath: '{{ shared_path }}/binlogs'
mariadb_dbdata_basepath: '/srv/mariadb/data'
mariadb_dbconfig_basepath: '/srv/mariadb/config'
mariadb_dbbackup_basepath: '{{ shared_path }}/backup'
mariadb_dbdata_basepath_volume: '/var/lib/mysql/'
mariadb_binlog_basepath_volume: '/var/lib/mysql-binlog'

_keybase: "{{ KEYBASE | default('/keybase/team/epfl_wp_' + inventory_environment) }}"
_secrets_file: "{{ _keybase }}/{{ SECRETS_FILE | default('secrets-mariadb.yml') }}"
mariadb_secrets: "{{ lookup('file', _secrets_file) | from_yaml }}"

