- tags: always
  include_vars: vars/mariadb-vars.yml

- name: Ensure MariaDB directories
  with_items:
    - '{{ mariadb_binlog_basepath }}/{{ item.name }}'
    - '{{ mariadb_dbdata_basepath }}/{{ item.name }}'
  ansible.builtin.file:
    state: directory
    path: '{{ item }}'
  tags:
    - mariadb.directories

- name: Ensure MariaDB container
  community.general.docker_container:
    name: 'mariadb_{{ item.name }}'
    state: started
    image: "mariadb:{{ mariadb_version }}"
    env:
      MARIADB_ROOT_PASSWORD: "{{ mariadb_secrets.root_password }}"
    ports:
      - "{{ item.port }}:3306"
    volumes:
      - "{{ mariadb_dbdata_basepath }}/{{ item.name }}:/var/lib/mysql"
  tags:
    - mariadb.container
