- include_tasks:
    file: vm-access.yml
    apply:
      tags:
        - vm
        - vm.access
  tags:
    - vm
    - vm.access

- include_tasks:
    file: vm-os.yml
    apply:
      tags:
        - vm
        - vm.os
  tags:
    - vm
    - vm.os
    - vm.motd
    - vm.os.upgrade

- name: Install Docker
  include_tasks:
    file: install-docker.yml
    apply:
      tags:
        - vm
        - vm.os
        - vm.os.docker
  tags:
    - vm
    - vm.os
    - vm.os.docker

- include_tasks:
    file: vm-volumes.yml
    apply:
      tags:
        - vm
        - vm.volumes
  tags:
    - vm
    - vm.volumes

- name: MariaDB
  with_items: "{{ mariadb_roles }}"
  include_tasks:
    file: docker-mariadb.yml
    apply:
      tags:
        - mariadb
  tags:
    - mariadb
    - mariadb.container
    - mariadb.directories
    - mariadb.rsync
    - mariadb.upgrade

- name: MariaDB administration
  include_tasks:
    file: mariadb-admin.yml
    apply:
      tags:
        - never
  tags:
    - mariadb.mycnf_file
