- tags: always
  include_vars: vars/mariadb-vars.yml

- name: Create database user for replica
  when: item.name == 'primary'
  community.mysql.mysql_user:
    name: "{{ mariadb_secrets.replicator.user }}"
    password: "{{ mariadb_secrets.replicator.password }}"
    priv: '*.*:REPLICATION SLAVE'
    state: present
    login_user: "{{ mariadb_secrets.superuser.user }}"
    login_password: "{{ mariadb_secrets.superuser.password }}"
  tags:
    - mariadb.replica

- name: "Run Backup on {{ item.name }}"
  when: item.name == 'primary'
  community.docker.docker_container_exec:
    container: "{{ container_name }}"
    command: "mariabackup --backup --target-dir={{ mariadb_dbbackup_basepath_volume }} --user={{ mariadb_secrets.superuser.user }} --password={{ mariadb_secrets.superuser.password }}"
  register: _upgrade_result
  tags:
    - mariadb.replica
