- tags: always
  include_vars: vars/access-vars.yml

- name: Ensure ssh keys for root
  ansible.posix.authorized_key:
    user: root
    state: "{{ item.state | default(present) }}"
    key: "https://github.com/{{ item.github }}.keys"
  with_items: "{{ SSH_KEYS }}"
