---

- name: Update all packages to their latest version
  ansible.builtin.apt:
    name: "*"
    state: latest
  when: >- 
    "vm.os.upgrade" in ansible_run_tags

- name: Convenient packages
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  with_items:
    - nmap
    - nfs-common
    - telnet
    - tmux
    - vim
    - git

- name: Change hostname
  ansible.builtin.hostname:
    name: "{{ inventory_hostname | regex_replace('\\..*$', '') }}" 

- name: Deploy the message of the day
  ansible.builtin.template:
    src: motd.txt
    dest: /etc/motd
    mode: 0644
  tags: vm.motd

- name: Add some colors to the shell
  replace:
    path: ~/.bashrc
    regexp: '^#force_color_prompt=yes$'
    replace: 'force_color_prompt=yes'


